### PR TITLE
Fixed NullReferenceException when closing file tab while reading

### PR DESCRIPTION
**Pull request by v0v4yk**

### CODE REVIEW

**Comment by ihtfw** [comment]
This would fix the issue, but it will wait until the read is completed, which could take time on large files. I think the closing logic should be redesigned with cancellation support, allowing it to be done lock-free and without waiting for the entire file to be read.

**Comment by v0v4yk** [comment]
Lock/unlock occurs at each iteration of the loop. At what point will it wait for the file to be read?

**Comment by ihtfw** [comment]
I missed that. It could potentially slow down reading. Could you please measure the impact on a large file (e.g., 500 MB)? What would the difference be?

**Comment by v0v4yk** [comment]
File size = 430 822 KB. Test with System.Diagnostics.StopWatch
Before commit - 00:00:54.4017281
After commit - 00:00:54.9583099

**Comment by v0v4yk** [comment]
File size = 662 626 KB
Before - 00:01:57.0219536
After - 00:01:57.2080300

**Pull request merged**
